In [7]:
#@title Setting Up Cuda on Windows

In [3]:
import torch
print(torch.__version__)

2.3.0+cu118


In [4]:
torch.cuda.is_available()

True

In [5]:
# Set the device to GPU
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(device)

cuda


In [6]:
torch.cuda.device_count()

1

### Moving tensors from CPU to GPU 

In [8]:
#create tensor
tensor = torch.tensor([1,2,3,4,5])
print(tensor)
print(tensor.device)

tensor([1, 2, 3, 4, 5])
cpu


In [9]:
tensor_on_gpu = tensor.to(device)
print(tensor_on_gpu)
print(tensor_on_gpu.device)

tensor([1, 2, 3, 4, 5], device='cuda:0')
cuda:0


### Moving back the Tensors from the GPU to the CPU

In [10]:
tensor_back_to_cpu = tensor_on_gpu.to('cpu')

In [12]:
tensor_back_to_cpu.numpy()

array([1, 2, 3, 4, 5], dtype=int64)

We can't directly convert the tensor on the GPU to a numpy array. We first need to move the tensor back to the CPU and then convert it to a numpy array.

In [15]:
tensor_on_gpu

tensor([1, 2, 3, 4, 5], device='cuda:0')